import {
  BarChart3Icon,
  BookOpenIcon,
  BotIcon,
  PackageIcon,
  FileDiffIcon,
  FolderOpenIcon,
  GlobeIcon,
  LogInIcon,
  LogOutIcon,
  MessageCirclePlus,
  MessageSquareIcon,
  MoonIcon,
  PanelLeftClose,
  PanelLeftOpen,
  ServerIcon,
  SettingsIcon,
  SquareTerminalIcon,
  SunIcon,
  UsersIcon,
  WandSparkles,
} from "lucide-react";
import type { QuickPickCommandIcon } from "@/quickpick/quickPickCommands.js";

export const QUICK_PICK_ICON_BY_KIND = {
  book: BookOpenIcon,
  bot: BotIcon,
  chart: BarChart3Icon,
  package: PackageIcon,
  browser: GlobeIcon,
  community: UsersIcon,
  diff: FileDiffIcon,
  feedback: MessageSquareIcon,
  folder: FolderOpenIcon,
  login: LogInIcon,
  logout: LogOutIcon,
  message: MessageCirclePlus,
  mcp: ServerIcon,
  settings: SettingsIcon,
  sidebarClose: PanelLeftClose,
  sidebarOpen: PanelLeftOpen,
  skills: WandSparkles,
  themeDark: MoonIcon,
  themeLight: SunIcon,
  terminal: SquareTerminalIcon,
} satisfies Record<QuickPickCommandIcon, typeof MessageCirclePlus>;
